from pydantic import BaseModel, Field
from typing import Optional

from app.config import LINK_ID_LENGTH_MIN, LINK_ID_LENGTH_MAX


class CreateLinkRequest(BaseModel):
    item_id: str
    expires_at: Optional[str] = None    # ISO 8601 datetime string, or null (no expiry)
    max_uses: Optional[int] = None      # null = unlimited
    max_clients: Optional[int] = None   # null = unlimited
    notes: Optional[str] = None
    flavor_enabled: bool = True         # enable/disable all visual flavor features
    background: Optional[str] = None   # specific background filename, null = random
    flavor_text: Optional[str] = None  # specific flavor text, null = random from pool


class RegisterRequest(BaseModel):
    client_id: str  # localStorage UUID generated by the browser


class EnvSettingsUpdate(BaseModel):
    """
    All fields optional — only keys actually present in the request are
    written. JELLYFIN_API_KEY/ADMIN_TOKEN are skipped if the submitted value
    matches the masked placeholder the GET response returned (see
    app/routes/settings.py), so re-saving the form without touching a secret
    field doesn't overwrite it with the placeholder text.
    """
    JELLYFIN_URL: Optional[str] = None
    JELLYFIN_API_KEY: Optional[str] = None
    ADMIN_TOKEN: Optional[str] = None
    PUBLIC_BASE_URL: Optional[str] = None
    DB_PATH: Optional[str] = None
    BACKGROUNDS_DIR: Optional[str] = None
    LINK_ID_LENGTH: Optional[int] = Field(default=None, ge=LINK_ID_LENGTH_MIN, le=LINK_ID_LENGTH_MAX)
    RATE_LIMIT_MAX_REQUESTS: Optional[int] = None
    RATE_LIMIT_WINDOW_SECONDS: Optional[int] = None


class ContentConfigSettingsUpdate(BaseModel):
    site_title: Optional[str] = None
    logo_path: Optional[str] = None
    glitch_enabled: Optional[bool] = None
    background_enabled: Optional[bool] = None
    logo_flash_enabled: Optional[bool] = None
    flavor_text_enabled: Optional[bool] = None
    flavor_texts: Optional[list[str]] = None


class SettingsUpdateRequest(BaseModel):
    env: Optional[EnvSettingsUpdate] = None
    content_config: Optional[ContentConfigSettingsUpdate] = None
