from pydantic import BaseModel
from typing import Optional


class CreateLinkRequest(BaseModel):
    item_id: str
    expires_at: Optional[str] = None   # ISO 8601 datetime string, or null (no expiry)
    max_uses: Optional[int] = None     # null = unlimited
    max_clients: Optional[int] = None  # null = unlimited
    notes: Optional[str] = None


class RegisterRequest(BaseModel):
    client_id: str  # localStorage UUID generated by the browser
